image:
  file: .gitpod.Dockerfile
tasks:
  - name: foo
    init: sleep 303
  # - name: tailscaled
  #   command: |
  #     if [ -n "${TAILSCALE_STATE_MYPROJECT}" ]; then
  #       # restore the tailscale state from gitpod user's env vars
  #       sudo mkdir -p /var/lib/tailscale
  #       echo "${TAILSCALE_STATE_MYPROJECT}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
  #     fi
  #     sudo tailscaled
  # - name: tailscale
  #   command: |
  #     if [ -n "${TAILSCALE_STATE_MYPROJECT}" ]; then
  #       sudo -E tailscale up
  #     else
  #       sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME// /-}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)"
  #       # store the tailscale state into gitpod user
  #       gp env TAILSCALE_STATE_MYPROJECT="$(sudo cat /var/lib/tailscale/tailscaled.state)"
  #     fi
  # - before: |
  #     echo "This runs first, in pre-build"
  #   init: |
  #     echo "This runs in pre-build"
  #   command: |
  #     echo "This runs on each workspace start"
  # - init: |
  #     echo "Sleeping... Long pre-build task"
  #     sleep 5s
  #     echo "Done sleeping!"
github:
  prebuilds:
    branches: true
    addCheck: prevent-merge-on-error
    addBadge: true
    addLabel: true
